<a href="https://colab.research.google.com/github/takrim1999/edge_project/blob/main/EdgeAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Packages Install Section

In [ ]:
!pip install numpy
!pip install pandas
!pip install scikit-learn

## Import Section

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

# Coding Section

## Practice numpy

In [ ]:
A = [
    [1,2],
    [2,3]
]

In [ ]:
B = [
    [7,4],
    [3,0]
]

In [ ]:
A = np.array(A)
B = np.array(B)

In [ ]:
print("Addition Matrix:\n",np.add(A,B))
print("Subtraction Matrix:\n",np.subtract(A,B))
print("Multiplied Matrix:\n",np.multiply(A,B))

Addition Matrix:
 [[8 6]
 [5 3]]
Subtraction Matrix:
 [[-6 -2]
 [-1  3]]
Multiplied Matrix:
 [[7 8]
 [6 0]]


+ COSINE SIMILARITY
+ SCIKIT LEARN

## Recommendation System

### Dummy Data

In [ ]:
data = {
    'user_id' : [1, 1, 1, 2, 2, 99, 99],
    'item_id' : [101, 102, 109, 102, 109, 101, 109],
    'amount' : [30, 10, 2, 15, 25, 2, 30]
}
df = pd.DataFrame(data)

In [ ]:
data

{'user_id': [1, 1, 1, 2, 2, 99, 99],
 'item_id': [101, 102, 109, 102, 109, 101, 109],
 'amount': [30, 10, 2, 15, 25, 2, 30]}

In [ ]:
table = df.pivot_table(index='user_id', columns='item_id', values='amount')
table = table.fillna(0)

In [ ]:
print(table)

item_id   101   102   109
user_id                  
1        30.0  10.0   2.0
2         0.0  15.0  25.0
99        2.0   0.0  30.0


In [ ]:
scaler = MinMaxScaler()
normalized = scaler.fit_transform(table)

In [ ]:
print(table)
print("")
print(normalized)
print("")
print(cosine_similarity(normalized))

item_id   101   102   109
user_id                  
1        30.0  10.0   2.0
2         0.0  15.0  25.0
99        2.0   0.0  30.0

[[1.         0.66666667 0.        ]
 [0.         1.         0.82142857]
 [0.06666667 0.         1.        ]]

[[1.         0.42863141 0.05534716]
 [0.42863141 1.         0.63333358]
 [0.05534716 0.63333358 1.        ]]


### Real time data

#### Pull The DataSet

In [ ]:
!mkdir data_set
!cp drive/MyDrive/edge_project/* ./data_set/

#### Work with Real Data (Movie Data)

In [ ]:
data = pd.read_csv('data_set/u.data',sep='\t',names=['user_id','movie_id','rating','timestamp'])
data = pd.DataFrame(data)

In [ ]:
data

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [ ]:
items = pd.read_csv('data_set/u.item',encoding="Latin 1",sep='|',usecols=[0,1],names=['movie_id','title'])
final_dataFrame = data.merge(items,on='movie_id')

In [ ]:
final_table = final_dataFrame.pivot_table(index='user_id', columns='movie_id', values='rating').fillna(0)
normalized_final_table = scaler.fit_transform(final_table)

In [ ]:
similairties = cosine_similarity(normalized_final_table)

AttributeError: 'numpy.ndarray' object has no attribute 'pivot_table'